/**
 * Contains a lookup table for mapping keypresses to events sent to statechart.
 */

const keydownLookup = {
  a: 'keydown.a',
  b: 'keydown.b',
  c: 'keydown.c',
  C: 'keydown.C',
  d: 'keydown.d',
  f: 'keydown.f',
  F: 'keydown.F',
  g: 'keydown.g',
  h: 'keydown.h',
  i: 'keydown.i',
  k: 'keydown.k',
  m: 'keydown.m',
  n: 'keydown.n',
  o: 'keydown.o',
  O: 'keydown.O',
  p: 'keydown.p',
  q: 'keydown.q',
  r: 'keydown.r',
  R: 'keydown.R',
  s: 'keydown.s',
  t: 'keydown.t',
  v: 'keydown.v',
  w: 'keydown.w',
  x: 'keydown.x',
  z: 'keydown.z',
  '-': 'keydown.-',
  '=': 'keydown.=',
  ']': 'keydown.]',
  '[': 'keydown.[',
  '}': 'keydown.}',
  '{': 'keydown.{',
  0: 'keydown.0',
  ' ': 'keydown.Space',
  Shift: 'keydown.Shift',
  Enter: 'keydown.Enter',
  Escape: 'keydown.Escape',
  ArrowLeft: 'keydown.left',
  ArrowRight: 'keydown.right',
  ArrowUp: 'keydown.up',
  ArrowDown: 'keydown.down',
};

export default keydownLookup;
