export const markerPanel = [
  { names: ['antigen-presenting cell', 'APC'], channels: ['HLADR'] },
  { names: ['B cell', 'B'], channels: ['CD19', 'CD20', 'CD45', 'VIM', 'HLADR'] },
  { names: ['T cell', 'T'], channels: ['CD3', 'CD4', 'CD45'] },
  { names: ['CD3 T cell', 'CD3T'], channels: ['CD3'] },
  { names: ['CD4 T cell', 'CD4T'], channels: ['CD3', 'CD4', 'VIM', 'CD45'] },
  { names: ['CD8 T cell', 'CD8T'], channels: ['CD8', 'CD3', 'VIM', 'CD45'] },
  { names: ['classical dendritic cell', 'cDC'], channels: ['CD11c'] },
  { names: ['dendritic cell', 'DC'], channels: ['CD11c', 'VIM', 'CD45', 'HLADR'] },
  { names: ['double negative T cell', 'dnT'], channels: ['CD3', 'CD45'] },
  { names: ['endothelial'], channels: ['CD31', 'VIM'] },
  { names: ['fibroblast'], channels: ['VIM'] },
  { names: ['gamma-delta T cell', 'gdT'], channels: ['gdTCR'] },
  { names: ['immune'], channels: ['CD45'] },
  { names: ['M2', 'M2 macrophage', 'M2 macro'], channels: ['CD163', 'CD206'] },
  { names: ['macrophage', 'macro'], channels: ['CD14', 'CD68'] },
  { names: ['mast cell', 'mast'], channels: ['Tryptase', 'VIM'] },
  { names: ['monocyte', 'mono'], channels: ['CD14'] },
  {
    names: ['monocyte derived dendritic cell', 'monoDC'],
    channels: ['CD14', 'CD11c', 'VIM', 'CD45', 'HLADR'],
  },
  { names: ['myeloid dendritic cell', 'mDC'], channels: ['CD11c'] },
  { names: ['myeloid'], channels: ['CD117', 'CD66'] },
  { names: ['myoepithelial', 'myoep'], channels: ['SMA', 'PanCK'] },
  { names: ['myofibroblast'], channels: ['SMA'] },
  { names: ['natural killer cell', 'NKC'], channels: ['CD56'] },
  { names: ['natural killer T cell', 'NKT'], channels: ['CD161', 'CD944', 'TCR'] },
  { names: ['neutrophil'], channels: ['MPO', 'CD15', 'CD45'] },
  { names: ['plasmacytoid dendritic cell', 'pDC'], channels: ['CD123'] },
  { names: ['T regulatory', 'Treg'], channels: ['CD4', 'FOXP3', 'CD26'] },
  { names: ['tumor', 'malignant'], channels: ['PanCK', 'ECAD'] },
];
